UsuariosBundle\Entity\Roles:
    type: entity
    table: null
    repositoryClass: UsuariosBundle\Repository\RolesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
