UsuariosBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: UsuariosBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        fbId:
            type: string
            length: 255
            unique: true
            column: fb_id
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        isActive:
            type: boolean
            column: is_active
        roles:
            type: string
            length: 255
    lifecycleCallbacks: {  }
